version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: $DB_CONTAINER_NAME
    restart: always
    environment:
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./backup:/data/db
      - ./seeds:/seeds
    networks:
      - db_network
  mongo-express:
    image: mongo-express
    container_name: $MONGO_EXPRESS_CONTAINER_NAME
    restart: always
    ports:
      - $MONGO_EXPRESS_PORT:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_INITDB_ROOT_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    networks:
      - db_network
networks:
  db_network:
    driver: bridge
